/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scribbler_io_RXTXScribblerPort_SerialOutputStream */

#ifndef _Included_scribbler_io_RXTXScribblerPort_SerialOutputStream
#define _Included_scribbler_io_RXTXScribblerPort_SerialOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
