/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scribbler_io_Zystem */

#ifndef _Included_scribbler_io_Zystem
#define _Included_scribbler_io_Zystem
#ifdef __cplusplus
extern "C" {
#endif
#undef scribbler_io_Zystem_SILENT_MODE
#define scribbler_io_Zystem_SILENT_MODE 0L
#undef scribbler_io_Zystem_FILE_MODE
#define scribbler_io_Zystem_FILE_MODE 1L
#undef scribbler_io_Zystem_NET_MODE
#define scribbler_io_Zystem_NET_MODE 2L
#undef scribbler_io_Zystem_MEX_MODE
#define scribbler_io_Zystem_MEX_MODE 3L
#undef scribbler_io_Zystem_PRINT_MODE
#define scribbler_io_Zystem_PRINT_MODE 4L
#undef scribbler_io_Zystem_J2EE_MSG_MODE
#define scribbler_io_Zystem_J2EE_MSG_MODE 5L
#undef scribbler_io_Zystem_J2SE_LOG_MODE
#define scribbler_io_Zystem_J2SE_LOG_MODE 6L
#ifdef __cplusplus
}
#endif
#endif
