/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scribbler_io_RXTXVersion */

#ifndef _Included_scribbler_io_RXTXVersion
#define _Included_scribbler_io_RXTXVersion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     scribbler_io_RXTXVersion
 * Method:    nativeGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scribbler_io_RXTXVersion_nativeGetVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
