/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scribbler_io_RXTXScribblerPort_MonitorThread */

#ifndef _Included_scribbler_io_RXTXScribblerPort_MonitorThread
#define _Included_scribbler_io_RXTXScribblerPort_MonitorThread
#ifdef __cplusplus
extern "C" {
#endif
#undef scribbler_io_RXTXScribblerPort_MonitorThread_MIN_PRIORITY
#define scribbler_io_RXTXScribblerPort_MonitorThread_MIN_PRIORITY 1L
#undef scribbler_io_RXTXScribblerPort_MonitorThread_NORM_PRIORITY
#define scribbler_io_RXTXScribblerPort_MonitorThread_NORM_PRIORITY 5L
#undef scribbler_io_RXTXScribblerPort_MonitorThread_MAX_PRIORITY
#define scribbler_io_RXTXScribblerPort_MonitorThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
