/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scribbler_io_RXTXScribblerPort_SerialInputStream */

#ifndef _Included_scribbler_io_RXTXScribblerPort_SerialInputStream
#define _Included_scribbler_io_RXTXScribblerPort_SerialInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef scribbler_io_RXTXScribblerPort_SerialInputStream_SKIP_BUFFER_SIZE
#define scribbler_io_RXTXScribblerPort_SerialInputStream_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
