//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using Microsoft.Dss.ServiceModel.DsspServiceBase;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml;
using ledarray = IPREGenericContracts.LEDarray;


namespace IPREGenericContracts.LEDarray
{
    
    /// <summary>
    /// Implementation class for Ledarray
    /// </summary>
    [DisplayName("Ledarray")]
    [Description("The Ledarray Service")]
    [Contract(Contract.Identifier)]
    public class LedarrayService : DsspServiceBase
    {
        /// <summary>
        /// _state
        /// </summary>
        private LedarrayState _state = new LedarrayState();
        /// <summary>
        /// _main Port
        /// </summary>
        [ServicePort("/ledarray", AllowMultipleInstances=false)]
        private LedarrayOperations _mainPort = new LedarrayOperations();
        /// <summary>
        /// Default Service Constructor
        /// </summary>
        public LedarrayService(DsspServiceCreationPort creationPort) : 
                base(creationPort)
        {
        }
        /// <summary>
        /// Service Start
        /// </summary>
        protected override void Start()
        {
			base.Start();
			// Add service specific initialization here.
        }

        /// <summary>
        /// Get Handler
        /// </summary>
        /// <param name="get"></param>
        /// <returns></returns>
        [ServiceHandler(ServiceHandlerBehavior.Concurrent)]
        public virtual IEnumerator<ITask> GetHandler(Get get)
        {
            get.ResponsePort.Post(_state);
            yield break;
        }

        /// <summary>
        /// SetSingle Handler
        /// </summary>
        /// <param name="get"></param>
        /// <returns></returns>
        [ServiceHandler(ServiceHandlerBehavior.Exclusive)]
        public virtual IEnumerator<ITask> SetSingleHandler(SetSingle get)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// SetVector Handler
        /// </summary>
        /// <param name="get"></param>
        /// <returns></returns>
        [ServiceHandler(ServiceHandlerBehavior.Exclusive)]
        public virtual IEnumerator<ITask> SetVectorHandler(SetVector get)
        {
            throw new NotImplementedException();
        }

    }
}
