//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using Microsoft.Dss.ServiceModel.DsspServiceBase;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml;
using tonegenerator = IPREGenericContracts.ToneGenerator;


namespace IPREGenericContracts.ToneGenerator
{
    
    /// <summary>
    /// Implementation class for ToneGenerator
    /// </summary>
    [DisplayName("ToneGenerator")]
    [Description("The ToneGenerator Service")]
    [Contract(Contract.Identifier)]
    public class ToneGeneratorService : DsspServiceBase
    {
        /// <summary>
        /// _state
        /// </summary>
        private ToneGeneratorState _state = new ToneGeneratorState();
        /// <summary>
        /// _main Port
        /// </summary>
        [ServicePort("/tonegenerator", AllowMultipleInstances=false)]
        private ToneGeneratorOperations _mainPort = new ToneGeneratorOperations();
        /// <summary>
        /// Default Service Constructor
        /// </summary>
        public ToneGeneratorService(DsspServiceCreationPort creationPort) : 
                base(creationPort)
        {
        }
        /// <summary>
        /// Service Start
        /// </summary>
        protected override void Start()
        {
			base.Start();
			// Add service specific initialization here.
        }
        /// <summary>
        /// Get Handler
        /// </summary>
        /// <param name="get"></param>
        /// <returns></returns>
        [ServiceHandler(ServiceHandlerBehavior.Concurrent)]
        public virtual IEnumerator<ITask> GetHandler(Get get)
        {
            get.ResponsePort.Post(_state);
            yield break;
        }

        /// <summary>
        /// PlayTone Handler
        /// </summary>
        [ServiceHandler(ServiceHandlerBehavior.Exclusive)]
        public virtual IEnumerator<ITask> PlayToneHandler(PlayTone request)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// PlayTone2 Handler
        /// </summary>
        [ServiceHandler(ServiceHandlerBehavior.Exclusive)]
        public virtual IEnumerator<ITask> PlayTone2Handler(PlayTone2 request)
        {
            throw new NotImplementedException();
        }
    }
}
