//------------------------------------------------------------------------------
// Scribbler Backup Monitor Service
//
//     This code was generated by the DssNewService tool.
//
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using Microsoft.Dss.ServiceModel.DsspServiceBase;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Security.Permissions;
using xml = System.Xml;
using System.Runtime.Serialization;
using W3C.Soap;


[assembly: ContractNamespace(IPRE.ScribblerBackupMonitor.Contract.Identifier, ClrNamespace = "IPRE.ScribblerBackupMonitor")]
namespace IPRE.ScribblerBackupMonitor
{

    public static class Contract
    {
        public const string Identifier = "http://www.roboteducation.org/scribblerbackupmonitor.html";
    }

    /// <summary>
    /// main service state
    /// </summary>
    [DataContract]
    public class ScribblerBackupMonitorState
    {
        /// <summary>
        /// how long to play tone in ms
        /// </summary>
        [DataMember]
        public int PlayDuration;

        /// <summary>
        /// how long to wait between tones in ms
        /// </summary>
        [DataMember]
        public int PauseDuration;

        /// <summary>
        /// frequency (in Hz)
        /// </summary>
        [DataMember]
        public int Frequency1;

        /// <summary>
        /// frequency (in Hz)
        /// </summary>
        [DataMember]
        public int Frequency2;
    }

    /// <summary>
    /// Main operations port
    /// </summary>
    public class ScribblerBackupMonitorOperations : PortSet<
        DsspDefaultLookup,
        DsspDefaultDrop,
        Get,
        Replace,
        Subscribe>
    {
    }

    /// <summary>
    /// http get
    /// returns entire state
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<ScribblerBackupMonitorState, Fault>> { }

    /// <summary>
    /// replaces entire state
    /// </summary>
    public class Replace : Replace<ScribblerBackupMonitorState, PortSet<DefaultReplaceResponseType, Fault>> { }

    /// <summary>
    /// general subscription
    /// notifications on any state change
    /// </summary>
    public class Subscribe : Subscribe<SubscribeRequestType, PortSet<SubscribeResponseType, Fault>> { }


}
