//------------------------------------------------------------------------------
// Scribbler Light Sensor Service
//
//     This code was generated by the DssNewService tool.
//
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using Microsoft.Dss.ServiceModel.DsspServiceBase;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Security.Permissions;
using xml = System.Xml;
using W3C.Soap;
using System.Runtime.Serialization;

using brick = IPRE.ScribblerBase.Proxy;
using analog = Microsoft.Robotics.Services.AnalogSensor.Proxy;

[assembly: ContractNamespace(IPRE.ScribblerHeartBeat.Contract.Identifier, ClrNamespace = "IPRE.ScribblerLightSensor")]
namespace IPRE.ScribblerLightSensor
{

    public static class Contract
    {
        public const string Identifier = "http://www.roboteducation.org/scribblerlightsensor.html";
    }


    /// <summary>
    /// Main state of service
    /// </summary>
    [DataContract]
    public class ScribblerLightSensorState
    {
        [DataMember]
        public analog.AnalogSensorState LeftSensor;

        [DataMember]
        public analog.AnalogSensorState CenterSensor;

        [DataMember]
        public analog.AnalogSensorState RightSensor;
    }

    /// <summary>
    /// Main operations port
    /// </summary>
    public class ScribblerLightSensorOperations : PortSet<
        DsspDefaultLookup,
        DsspDefaultDrop,
        Get,
        Replace,
        Subscribe>
    {
    }

    /// <summary>
    /// http get
    /// returns entire state
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<ScribblerLightSensorState, Fault>> { }

    /// <summary>
    /// replaces entire state
    /// </summary>
    public class Replace : Replace<ScribblerLightSensorState, PortSet<DefaultReplaceResponseType, Fault>> { }

    /// <summary>
    /// general subscription
    /// notifications on any state change
    /// </summary>
    public class Subscribe : Subscribe<SubscribeRequestType, PortSet<SubscribeResponseType, Fault>> { }

}
