//------------------------------------------------------------------------------
// ScribblerTypes.cs
//
//     This code was generated by the DssNewService tool.
//
//      Ben Axelrod 08/28/2006
//
//------------------------------------------------------------------------------
using Microsoft.Ccr.Core;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using W3C.Soap;

[assembly: ContractNamespace(IPRE.ScribblerBase.Contract.Identifier, ClrNamespace = "IPRE.ScribblerBase")]
namespace IPRE.ScribblerBase
{
    
    public static class Contract
    {
        public const string Identifier = "http://www.roboteducation.org/scribblerbase.html";
    }

    /// <summary>
    /// Main operations port
    /// </summary>
    public class ScribblerOperations : PortSet<
        DsspDefaultLookup, 
        DsspDefaultDrop, 
        Get, 
        Replace,
        SetMotor,
        SetLED,
        PlayTone,
        SetName,
        //ConfigureSensor,
        SelectiveSubscribe, //IMPORTANT: Because SelectiveSubscribe inherits from Subscribe, it must go on top.
        Subscribe>
    {
    }

    public class SendScribblerCommand : Submit<ScribblerCommand, PortSet<ScribblerResponse, Fault>>
    {
        public SendScribblerCommand() { }
        public SendScribblerCommand(ScribblerCommand cmd)
        {
            this.Body = cmd;
        }
    }

    /// <summary>
    /// http get
    /// returns entire state
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<ScribblerState, Fault>> { }

    /// <summary>
    /// replaces entire state
    /// </summary>
    public class Replace : Replace<ScribblerState, PortSet<DefaultReplaceResponseType, Fault>> { }

    /// <summary>
    /// a motor command
    /// </summary>
    public class SetMotor : Update<SetMotorBody, PortSet<DefaultUpdateResponseType, Fault>> { }

    ///// <summary>
    ///// configures 1 light sensor for subscriptions
    ///// </summary>
    //public class ConfigureSensor : Update<ConfigureSensorBody, PortSet<DefaultUpdateResponseType, Fault>> { }

    /// <summary>
    /// general subscription
    /// notifications on any state change
    /// </summary>
    public class Subscribe : Subscribe<SubscribeRequestType, PortSet<SubscribeResponseType, Fault>> { }

    /// <summary>
    /// a selective subscription
    /// subscribe to one or many sensor updates
    /// </summary>
    public class SelectiveSubscribe : Subscribe<MySubscribeRequestType, PortSet<SubscribeResponseType, Fault>> { }

    /// <summary>
    /// sends an LED message to Scribbler
    /// </summary>
    public class SetLED : Update<SetLedBody, PortSet<DefaultUpdateResponseType, Fault>> { }

    /// <summary>
    /// Plays a tone on the scribbler
    /// </summary>
    public class PlayTone : Update<PlayToneBody, PortSet<DefaultUpdateResponseType, Fault>> { }

    /// <summary>
    /// Plays a tone on the scribbler
    /// </summary>
    public class SetName : Update<SetNameBody, PortSet<DefaultUpdateResponseType, Fault>> { }
}
