//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using tonegenerator = IPREGenericContracts.ToneGenerator;


namespace IPREGenericContracts.ToneGenerator
{
    
    /// <summary>
    /// ToneGenerator Contract class
    /// </summary>
    public sealed class Contract
    {
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        public const String Identifier = "http://schemas.tempuri.org/2007/06/tonegenerator.html";
    }

    /// <summary>
    /// The ToneGenerator State
    /// </summary>
    [DataContract()]
    public class ToneGeneratorState
    {
        private bool _playingTone;

        [DataMember]
        public bool PlayingTone
        {
            get { return this._playingTone; }
            set { this._playingTone = value; }
        }
    }

    /// <summary>
    /// ToneGenerator Main Operations Port
    /// </summary>
    public class ToneGeneratorOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get, PlayTone, PlayTone2>
    {
        /// <summary>
        /// Required Lookup request body type
        /// </summary>
        public virtual Microsoft.Ccr.Core.PortSet<Microsoft.Dss.ServiceModel.Dssp.LookupResponse,W3C.Soap.Fault> DsspDefaultLookup()
        {
            Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup op = new Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(op);
            return op.ResponsePort;

        }
        /// <summary>
        /// Post Dssp Default Lookup and return the response port.
        /// </summary>
        public virtual Microsoft.Ccr.Core.PortSet<Microsoft.Dss.ServiceModel.Dssp.LookupResponse,W3C.Soap.Fault> DsspDefaultLookup(Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body)
        {
            Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup op = new Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup();
            op.Body = body ?? new Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            this.Post(op);
            return op.ResponsePort;

        }
        /// <summary>
        /// A request to drop the service.
        /// </summary>
        public virtual Microsoft.Ccr.Core.PortSet<Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType,W3C.Soap.Fault> DsspDefaultDrop()
        {
            Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop op = new Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(op);
            return op.ResponsePort;

        }
        /// <summary>
        /// Post Dssp Default Drop and return the response port.
        /// </summary>
        public virtual Microsoft.Ccr.Core.PortSet<Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType,W3C.Soap.Fault> DsspDefaultDrop(Microsoft.Dss.ServiceModel.Dssp.DropRequestType body)
        {
            Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop op = new Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop();
            op.Body = body ?? new Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            this.Post(op);
            return op.ResponsePort;

        }
        /// <summary>
        /// Required Get body type
        /// </summary>
        public virtual Microsoft.Ccr.Core.PortSet<ToneGeneratorState,W3C.Soap.Fault> Get()
        {
            Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            Get op = new Get(body);
            this.Post(op);
            return op.ResponsePort;

        }
        /// <summary>
        /// Post Get and return the response port.
        /// </summary>
        public virtual Microsoft.Ccr.Core.PortSet<ToneGeneratorState,W3C.Soap.Fault> Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body)
        {
            Get op = new Get();
            op.Body = body ?? new Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            this.Post(op);
            return op.ResponsePort;

        }
    }
    /// <summary>
    /// ToneGenerator Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<ToneGeneratorState, Fault>>
    {
        /// <summary>
        /// ToneGenerator Get Operation
        /// </summary>
        public Get()
        {
        }
        /// <summary>
        /// ToneGenerator Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        /// <summary>
        /// ToneGenerator Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<ToneGeneratorState,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }

    /// <summary>
    /// Operation PlayTone: Plays a tone for a specified amount of time
    /// </summary>
    public class PlayTone : Update<PlayToneRequest, PortSet<DefaultUpdateResponseType, Fault>>
    {
        public PlayTone()
        {
        }

        public PlayTone(PlayToneRequest req)
            : base(req)
        {
        }
    }

    /// <summary>
    /// Operation PlayTone2: Plays a dual tone for a specified amount of time
    /// </summary>
    public class PlayTone2 : Update<PlayTone2Request, PortSet<DefaultUpdateResponseType, Fault>>
    {
    }

    /// <summary>
    /// Body of the PlayTone message
    /// </summary>
    [DataContract]
    [DataMemberConstructor]
    public class PlayToneRequest
    {
        private int _frequency;
        private int _duration;

        /// <summary>
        /// The frequency of the note to play
        /// </summary>
        [DataMember]
        public int Frequency
        {
            get { return _frequency; }
            set { _frequency = value; }
        }

        /// <summary>
        /// How long to play the note
        /// </summary>
        [DataMember]
        public int Duration
        {
            get { return _duration; }
            set { _duration = value; }
        }
    }

    /// <summary>
    /// Body of the PlayTone2 message
    /// </summary>
    [DataContract]
    [DataMemberConstructor]
    public class PlayTone2Request
    {
        private int _frequency1;
        private int _frequency2;
        private int _duration;

        /// <summary>
        /// The frequency of the note to play
        /// </summary>
        [DataMember]
        public int Frequency1
        {
            get { return _frequency1; }
            set { _frequency1 = value; }
        }

        /// <summary>
        /// The frequency of the note to play
        /// </summary>
        [DataMember]
        public int Frequency2
        {
            get { return _frequency2; }
            set { _frequency2 = value; }
        }

        /// <summary>
        /// How long to play the tone
        /// </summary>
        [DataMember]
        public int Duration
        {
            get { return _duration; }
            set { _duration = value; }
        }
    }
}
