//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     DSS Runtime Version: 2.0.730.3
//     CLR Runtime Version: 2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using Microsoft.Dss.ServiceModel.DsspServiceBase;
using submgr = Microsoft.Dss.Services.SubscriptionManager;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml;
using W3C.Soap;

namespace Myro.Services.Generic.Vector
{
    /// <summary>
    /// Implementation class for Vector
    /// </summary>
    [DisplayName("Vector")]
    [Description("A Generic Vector Service")]
    [Contract(Contract.Identifier)]
    public class VectorService : DsspServiceBase
    {

        /// <summary>
        /// _state
        /// </summary>
        [ServiceState()]
        protected VectorState _state = new VectorState();

        /// <summary>
        /// _main Port
        /// </summary>
        [ServicePort("/vector", AllowMultipleInstances = false)]
        protected VectorOperations _operationsPort = new VectorOperations();
        protected VectorOperations OperationsPort { get { return _operationsPort; } private set { _operationsPort = value; } }

        [Partner("SubMgr",
            Contract = submgr.Contract.Identifier,
            CreationPolicy = PartnerCreationPolicy.CreateAlways,
            Optional = false)]
        private submgr.SubscriptionManagerPort _subMgrPort = new submgr.SubscriptionManagerPort();

        /// <summary>
        /// Default Service Constructor
        /// </summary>
        public VectorService(DsspServiceCreationPort creationPort) :
            base(creationPort)
        {
        }

        /// <summary>
        /// Service Start
        /// </summary>
        protected override void Start()
        {
            base.Start();
        }

        [ServiceHandler(ServiceHandlerBehavior.Exclusive)]
        public virtual IEnumerator<ITask> ReplaceHandler(Replace replace)
        {
            _state = replace.Body;
            replace.ResponsePort.Post(DefaultReplaceResponseType.Instance);
            SendNotification<Replace>(replace);
            yield break;
        }

        [ServiceHandler(ServiceHandlerBehavior.Exclusive)]
        public virtual IEnumerator<ITask> SetHandler(Set set)
        {
            if (set.Body.Index >= 0 && set.Body.Index < _state.Values.Count)
            {
                _state.Values[set.Body.Index] = set.Body.Value;
                _state.Timestamp = set.Body.Timestamp;
                set.ResponsePort.Post(DefaultUpdateResponseType.Instance);
                SendNotification<Set>(set);
            }
            else
            {
                Fault fault = new Fault();
                fault.Reason = new ReasonText[1];
                fault.Reason[0] = new ReasonText();
                fault.Reason[0].Value = "Vector element index out of bounds";
                set.ResponsePort.Post(fault);
            }
            yield break;
        }

        [ServiceHandler(ServiceHandlerBehavior.Exclusive)]
        public virtual IEnumerator<ITask> SetAllHandler(SetAll setAll)
        {
            _state.Values = setAll.Body.Values;
            _state.Timestamp = setAll.Body.Timestamp;
            setAll.ResponsePort.Post(DefaultUpdateResponseType.Instance);
            SendNotification<SetAll>(setAll);
            yield break;
        }

        [ServiceHandler(ServiceHandlerBehavior.Exclusive)]
        public virtual IEnumerator<ITask> SubscribeHandler(Subscribe subscribe)
        {
            yield return Arbiter.Choice(
                SubscribeHelper(_subMgrPort, subscribe.Body, subscribe.ResponsePort),
                delegate(SuccessResult success)
                {
                    base.SendNotification<Replace>(_subMgrPort, subscribe.Body.Subscriber, _state);
                },
                delegate(Exception error)
                {
                    base.LogError("Error adding subscriber " + subscribe.Body.Subscriber, error);
                });
        }

        protected void SendNotification<T>(T message) where T:DsspOperation
        {
            base.SendNotification<T>(_subMgrPort, message);
        }

    }
}
