
IronTextBox.dll:
	MONO_PATH=../libs /usr/local/bin/gmcs -recurse:*.cs -r:System.Data -r:System.Drawing -r:System.Windows.Forms -r:../libs/IronPython -r:../libs/Microsoft.Scripting -target:library -out:IronTextBox.dll
	cp IronTextBox.dll ../libs/
