//------------------------------------------------------------------------------
// Scribbler Line Sensor Service
//
//     This code was generated by the DssNewService tool.
//
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using Microsoft.Dss.ServiceModel.DsspServiceBase;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Security.Permissions;
using xml = System.Xml;
using W3C.Soap;

using brick = IPRE.ScribblerBase.Proxy;


namespace IPRE.ScribblerLineSensor
{

    public static class Contract
    {
        public const string Identifier = "http://www.roboteducation.org/scribblerlinesensor.html";
    }


    /// <summary>
    /// Main state of service
    /// </summary>
    [DataContract]
    public class ScribblerLineSensorState
    {
        /// <summary>
        /// true when either line sensor detects a black line
        /// </summary>
        [DataMember]
        public bool LineDetected;

        /// <summary>
        /// -1 if only the left line sensor sees the line
        /// 0 if both line sensors see the line
        /// 1 if only the right line sensor sees the line
        /// </summary>
        [DataMember]
        public int LocationOfLine;

        /// <summary>
        /// last time state was updated
        /// </summary>
        [DataMember]
        public DateTime TimeStamp;
    }

    /// <summary>
    /// Main operations port
    /// </summary>
    public class ScribblerLineSensorOperations : PortSet<
        DsspDefaultLookup,
        DsspDefaultDrop,
        Get,
        Replace,
        Subscribe>
    {
    }

    /// <summary>
    /// http get
    /// returns entire state
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<ScribblerLineSensorState, Fault>> { }

    /// <summary>
    /// replaces entire state
    /// </summary>
    public class Replace : Replace<ScribblerLineSensorState, PortSet<DefaultReplaceResponseType, Fault>> { }

    /// <summary>
    /// general subscription
    /// notifications on any state change
    /// </summary>
    public class Subscribe : Subscribe<SubscribeRequestType, PortSet<SubscribeResponseType, Fault>> { }

}
