//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     DSS Runtime Version: 2.0.730.3
//     CLR Runtime Version: 2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using myroinfo = Robotics.MyroInfo;


namespace Robotics.MyroInfo
{
    
    
    /// <summary>
    /// MyroInfo Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        [DataMember()]
        public const String Identifier = "http://schemas.tempuri.org/2008/05/myroinfo.html";
    }
    
    /// <summary>
    /// The MyroInfo State
    /// </summary>
    [DataContract()]
    public class MyroInfoState
    {
        [DataMember]
        public int NumLEDs { get; set; }
        public MyroInfoState()
        {
            NumLEDs = 3;
        }
    }
    
    /// <summary>
    /// MyroInfo Main Operations Port
    /// </summary>
    [ServicePort()]
    public class MyroInfoOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get, Replace>
    {
    }
    
    /// <summary>
    /// MyroInfo Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<MyroInfoState, Fault>>
    {
        
        /// <summary>
        /// MyroInfo Get Operation
        /// </summary>
        public Get()
        {
        }
        
        /// <summary>
        /// MyroInfo Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        
        /// <summary>
        /// MyroInfo Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<MyroInfoState,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }

    /// <summary>
    /// MyroInfo Set operation
    /// </summary>
    public class Replace : Replace<MyroInfoState, PortSet<DefaultReplaceResponseType, Fault>>
    {
    }
}
